"""Add read_at to reading_history

Revision ID: fae376b91902
Revises: bb3e1a9f8257
Create Date: 2026-08-06 00:20:09.170247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fae376b91902'
down_revision: Union[str, Sequence[str], None] = 'bb3e1a9f8257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading_history', sa.Column('read_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reading_history', 'read_at')
    # ### end Alembic commands ###
